
--DELETE FROM `factory` WHERE `factorycode`= 'f1';
--INSERT INTO `chori`.`factory` (`FACTORYCODE`, `CREATOR`, `SHORTNAME`, `LONGNAME`, `ADDRESS`, `TEL`, `FAX`, `TAXNO`, `STATUS`, `CREATEDATE`) VALUES ('f2', NULL, 'f2', NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON DUPLICATE KEY UPDATE `FACTORYCODE`= 'f2';
--INSERT INTO `chori`.`factory` (`FACTORYCODE`, `CREATOR`, `SHORTNAME`, `LONGNAME`, `ADDRESS`, `TEL`, `FAX`, `TAXNO`, `STATUS`, `CREATEDATE`) VALUES ('f3', NULL, 'f3', NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON DUPLICATE KEY UPDATE `FACTORYCODE`= 'f3';
DELETE FROM `chori`.`factorycontact` WHERE `factorycontact`.`FACTORYCODE` = 'DV';
DELETE FROM `chori`.`factory` WHERE `factory`.`FACTORYCODE` = 'DV';
INSERT INTO `chori`.`factory` (`FACTORYCODE`, `CREATOR`, `SHORTNAME`, `LONGNAME`, `ADDRESS`, `TEL`, `FAX`, `TAXNO`, `STATUS`, `CREATEDATE`) VALUES ('FacCode1', NULL, 'Fac Code 1', NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON DUPLICATE KEY UPDATE `FACTORYCODE`= 'FacCode1';
INSERT INTO `chori`.`factorycontact` (`FACTORYCONTACTCODE`, `FACTORYCODE`, `CREATOR`, `NAME`, `EMAIL`, `CREATEDATE`) VALUES (NULL, 'FacCode1', NULL, 'dude1', 'dude1@gmail.com', NULL) ON DUPLICATE KEY UPDATE `FACTORYCODE`= 'FacCode1';