package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accessoryordersignature generated by hbm2java
 */
@Entity
@Table(name = "accessoryordersignature")
public class Accessoryordersignature implements java.io.Serializable {

	private Integer accordersigncode;
	private User user;
	private String name;
	private String text1;
	private String text2;
	private String imgurl;
	private Date createdate;

	public Accessoryordersignature() {
	}

	public Accessoryordersignature(User user, String name, String text1, String text2, String imgurl, Date createdate) {
		this.user = user;
		this.name = name;
		this.text1 = text1;
		this.text2 = text2;
		this.imgurl = imgurl;
		this.createdate = createdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACCORDERSIGNCODE", unique = true, nullable = false)
	public Integer getAccordersigncode() {
		return this.accordersigncode;
	}

	public void setAccordersigncode(Integer accordersigncode) {
		this.accordersigncode = accordersigncode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TEXT1", length = 100)
	public String getText1() {
		return this.text1;
	}

	public void setText1(String text1) {
		this.text1 = text1;
	}

	@Column(name = "TEXT2", length = 100)
	public String getText2() {
		return this.text2;
	}

	public void setText2(String text2) {
		this.text2 = text2;
	}

	@Column(name = "IMGURL", length = 500)
	public String getImgurl() {
		return this.imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
