package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccessoryformdetailId generated by hbm2java
 */
@Embeddable
public class AccessoryformdetailId implements java.io.Serializable {

	private String accessorycode;
	private String accessoryformcode;

	public AccessoryformdetailId() {
	}

	public AccessoryformdetailId(String accessorycode, String accessoryformcode) {
		this.accessorycode = accessorycode;
		this.accessoryformcode = accessoryformcode;
	}

	@Column(name = "ACCESSORYCODE", nullable = false, length = 100)
	public String getAccessorycode() {
		return this.accessorycode;
	}

	public void setAccessorycode(String accessorycode) {
		this.accessorycode = accessorycode;
	}

	@Column(name = "ACCESSORYFORMCODE", nullable = false, length = 20)
	public String getAccessoryformcode() {
		return this.accessoryformcode;
	}

	public void setAccessoryformcode(String accessoryformcode) {
		this.accessoryformcode = accessoryformcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccessoryformdetailId))
			return false;
		AccessoryformdetailId castOther = (AccessoryformdetailId) other;

		return ((this.getAccessorycode() == castOther.getAccessorycode())
				|| (this.getAccessorycode() != null && castOther.getAccessorycode() != null
						&& this.getAccessorycode().equals(castOther.getAccessorycode())))
				&& ((this.getAccessoryformcode() == castOther.getAccessoryformcode())
						|| (this.getAccessoryformcode() != null && castOther.getAccessoryformcode() != null
								&& this.getAccessoryformcode().equals(castOther.getAccessoryformcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAccessorycode() == null ? 0 : this.getAccessorycode().hashCode());
		result = 37 * result + (getAccessoryformcode() == null ? 0 : this.getAccessoryformcode().hashCode());
		return result;
	}

}
