package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accessorysupplier generated by hbm2java
 */
@Entity
@Table(name = "accessorysupplier")
public class Accessorysupplier implements java.io.Serializable {

	private String accsuppliercode;
	private User user;
	private String shortname;
	private String longname;
	private String address;
	private String tel;
	private String fax;
	private String taxno;
	private String email;
	private String status;
	private Date createdate;
	private String remark;
	private Set<Orderinternalaccessory> orderinternalaccessories = new HashSet<Orderinternalaccessory>(0);
	private Set<Accessoryprice> accessoryprices = new HashSet<Accessoryprice>(0);
	private Set<Accessorysuppliercontact> accessorysuppliercontacts = new HashSet<Accessorysuppliercontact>(0);
	private Set<Orderexternalaccessory> orderexternalaccessories = new HashSet<Orderexternalaccessory>(0);

	public Accessorysupplier() {
	}

	public Accessorysupplier(String accsuppliercode, String shortname) {
		this.accsuppliercode = accsuppliercode;
		this.shortname = shortname;
	}

	public Accessorysupplier(String accsuppliercode, User user, String shortname, String longname, String address,
			String tel, String fax, String taxno, String email, String status, Date createdate, String remark,
			Set<Orderinternalaccessory> orderinternalaccessories, Set<Accessoryprice> accessoryprices,
			Set<Accessorysuppliercontact> accessorysuppliercontacts,
			Set<Orderexternalaccessory> orderexternalaccessories) {
		this.accsuppliercode = accsuppliercode;
		this.user = user;
		this.shortname = shortname;
		this.longname = longname;
		this.address = address;
		this.tel = tel;
		this.fax = fax;
		this.taxno = taxno;
		this.email = email;
		this.status = status;
		this.createdate = createdate;
		this.remark = remark;
		this.orderinternalaccessories = orderinternalaccessories;
		this.accessoryprices = accessoryprices;
		this.accessorysuppliercontacts = accessorysuppliercontacts;
		this.orderexternalaccessories = orderexternalaccessories;
	}

	@Id

	@Column(name = "ACCSUPPLIERCODE", unique = true, nullable = false, length = 50)
	public String getAccsuppliercode() {
		return this.accsuppliercode;
	}

	public void setAccsuppliercode(String accsuppliercode) {
		this.accsuppliercode = accsuppliercode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "SHORTNAME", nullable = false, length = 50)
	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	@Column(name = "LONGNAME", length = 100)
	public String getLongname() {
		return this.longname;
	}

	public void setLongname(String longname) {
		this.longname = longname;
	}

	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "TEL", length = 50)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "FAX", length = 50)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "TAXNO", length = 50)
	public String getTaxno() {
		return this.taxno;
	}

	public void setTaxno(String taxno) {
		this.taxno = taxno;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accessorysupplier")
	public Set<Orderinternalaccessory> getOrderinternalaccessories() {
		return this.orderinternalaccessories;
	}

	public void setOrderinternalaccessories(Set<Orderinternalaccessory> orderinternalaccessories) {
		this.orderinternalaccessories = orderinternalaccessories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accessorysupplier")
	public Set<Accessoryprice> getAccessoryprices() {
		return this.accessoryprices;
	}

	public void setAccessoryprices(Set<Accessoryprice> accessoryprices) {
		this.accessoryprices = accessoryprices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accessorysupplier")
	public Set<Accessorysuppliercontact> getAccessorysuppliercontacts() {
		return this.accessorysuppliercontacts;
	}

	public void setAccessorysuppliercontacts(Set<Accessorysuppliercontact> accessorysuppliercontacts) {
		this.accessorysuppliercontacts = accessorysuppliercontacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accessorysupplier")
	public Set<Orderexternalaccessory> getOrderexternalaccessories() {
		return this.orderexternalaccessories;
	}

	public void setOrderexternalaccessories(Set<Orderexternalaccessory> orderexternalaccessories) {
		this.orderexternalaccessories = orderexternalaccessories;
	}

}
