package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accessoryform generated by hbm2java
 */
@Entity
@Table(name = "accessoryform")
public class Accessoryform implements java.io.Serializable {

	private String accessoryformcode;
	private User user;
	private String description;
	private Date createdate;
	private Set<Accessoryformdetail> accessoryformdetails = new HashSet<Accessoryformdetail>(0);

	public Accessoryform() {
	}

	public Accessoryform(String accessoryformcode) {
		this.accessoryformcode = accessoryformcode;
	}

	public Accessoryform(String accessoryformcode, User user, String description, Date createdate,
			Set<Accessoryformdetail> accessoryformdetails) {
		this.accessoryformcode = accessoryformcode;
		this.user = user;
		this.description = description;
		this.createdate = createdate;
		this.accessoryformdetails = accessoryformdetails;
	}

	@Id

	@Column(name = "ACCESSORYFORMCODE", unique = true, nullable = false, length = 20)
	public String getAccessoryformcode() {
		return this.accessoryformcode;
	}

	public void setAccessoryformcode(String accessoryformcode) {
		this.accessoryformcode = accessoryformcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accessoryform")
	public Set<Accessoryformdetail> getAccessoryformdetails() {
		return this.accessoryformdetails;
	}

	public void setAccessoryformdetails(Set<Accessoryformdetail> accessoryformdetails) {
		this.accessoryformdetails = accessoryformdetails;
	}

}
