package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccessoryconsumptionId generated by hbm2java
 */
@Embeddable
public class AccessoryconsumptionId implements java.io.Serializable {

	private String factorycode;
	private String accessorycode;

	public AccessoryconsumptionId() {
	}

	public AccessoryconsumptionId(String factorycode, String accessorycode) {
		this.factorycode = factorycode;
		this.accessorycode = accessorycode;
	}

	@Column(name = "FACTORYCODE", nullable = false, length = 50)
	public String getFactorycode() {
		return this.factorycode;
	}

	public void setFactorycode(String factorycode) {
		this.factorycode = factorycode;
	}

	@Column(name = "ACCESSORYCODE", nullable = false, length = 100)
	public String getAccessorycode() {
		return this.accessorycode;
	}

	public void setAccessorycode(String accessorycode) {
		this.accessorycode = accessorycode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccessoryconsumptionId))
			return false;
		AccessoryconsumptionId castOther = (AccessoryconsumptionId) other;

		return ((this.getFactorycode() == castOther.getFactorycode()) || (this.getFactorycode() != null
				&& castOther.getFactorycode() != null && this.getFactorycode().equals(castOther.getFactorycode())))
				&& ((this.getAccessorycode() == castOther.getAccessorycode())
						|| (this.getAccessorycode() != null && castOther.getAccessorycode() != null
								&& this.getAccessorycode().equals(castOther.getAccessorycode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFactorycode() == null ? 0 : this.getFactorycode().hashCode());
		result = 37 * result + (getAccessorycode() == null ? 0 : this.getAccessorycode().hashCode());
		return result;
	}

}
