package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accessoryconsumption generated by hbm2java
 */
@Entity
@Table(name = "accessoryconsumption")
public class Accessoryconsumption implements java.io.Serializable {

	private AccessoryconsumptionId id;
	private Accessory accessory;
	private Factory factory;
	private User user;
	private Float consumption;
	private Date createdate;

	public Accessoryconsumption() {
	}

	public Accessoryconsumption(AccessoryconsumptionId id, Accessory accessory, Factory factory, User user) {
		this.id = id;
		this.accessory = accessory;
		this.factory = factory;
		this.user = user;
	}

	public Accessoryconsumption(AccessoryconsumptionId id, Accessory accessory, Factory factory, User user,
			Float consumption, Date createdate) {
		this.id = id;
		this.accessory = accessory;
		this.factory = factory;
		this.user = user;
		this.consumption = consumption;
		this.createdate = createdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "factorycode", column = @Column(name = "FACTORYCODE", nullable = false, length = 50)),
			@AttributeOverride(name = "accessorycode", column = @Column(name = "ACCESSORYCODE", nullable = false, length = 100)) })
	public AccessoryconsumptionId getId() {
		return this.id;
	}

	public void setId(AccessoryconsumptionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCESSORYCODE", nullable = false, insertable = false, updatable = false)
	public Accessory getAccessory() {
		return this.accessory;
	}

	public void setAccessory(Accessory accessory) {
		this.accessory = accessory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FACTORYCODE", nullable = false, insertable = false, updatable = false)
	public Factory getFactory() {
		return this.factory;
	}

	public void setFactory(Factory factory) {
		this.factory = factory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "CONSUMPTION", precision = 12, scale = 0)
	public Float getConsumption() {
		return this.consumption;
	}

	public void setConsumption(Float consumption) {
		this.consumption = consumption;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
