package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accessoryprice generated by hbm2java
 */
@Entity
@Table(name = "accessoryprice")
public class Accessoryprice implements java.io.Serializable {

	private Integer accessorypricecode;
	private Accessory accessory;
	private Accessorysupplier accessorysupplier;
	private Currency currency;
	private User user;
	private Date fromdate;
	private Date todate;
	private Float unitpriceperunit;
	private Date createdate;
	private String remark;

	public Accessoryprice() {
	}

	public Accessoryprice(Accessory accessory, Accessorysupplier accessorysupplier) {
		this.accessory = accessory;
		this.accessorysupplier = accessorysupplier;
	}

	public Accessoryprice(Accessory accessory, Accessorysupplier accessorysupplier, Currency currency, User user,
			Date fromdate, Date todate, Float unitpriceperunit, Date createdate, String remark) {
		this.accessory = accessory;
		this.accessorysupplier = accessorysupplier;
		this.currency = currency;
		this.user = user;
		this.fromdate = fromdate;
		this.todate = todate;
		this.unitpriceperunit = unitpriceperunit;
		this.createdate = createdate;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACCESSORYPRICECODE", unique = true, nullable = false)
	public Integer getAccessorypricecode() {
		return this.accessorypricecode;
	}

	public void setAccessorypricecode(Integer accessorypricecode) {
		this.accessorypricecode = accessorypricecode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCESSORYCODE", nullable = false)
	public Accessory getAccessory() {
		return this.accessory;
	}

	public void setAccessory(Accessory accessory) {
		this.accessory = accessory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCSUPPLIERCODE", nullable = false)
	public Accessorysupplier getAccessorysupplier() {
		return this.accessorysupplier;
	}

	public void setAccessorysupplier(Accessorysupplier accessorysupplier) {
		this.accessorysupplier = accessorysupplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCYCODE")
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FROMDATE", length = 19)
	public Date getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(Date fromdate) {
		this.fromdate = fromdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TODATE", length = 19)
	public Date getTodate() {
		return this.todate;
	}

	public void setTodate(Date todate) {
		this.todate = todate;
	}

	@Column(name = "UNITPRICEPERUNIT", precision = 20, scale = 4)
	public Float getUnitpriceperunit() {
		return this.unitpriceperunit;
	}

	public void setUnitpriceperunit(Float unitpriceperunit) {
		this.unitpriceperunit = unitpriceperunit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
