package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "color")
public class Color implements java.io.Serializable {

	private String colorcode;
	private User user;
	private String description;
	private Date createdate;
	private Set<Piassigninternalaccessoriesdetail> piassigninternalaccessoriesdetails = new HashSet<Piassigninternalaccessoriesdetail>(
			0);
	private Set<Piassignfabricdetail> piassignfabricdetails = new HashSet<Piassignfabricdetail>(0);
	private Set<Fpidetail> fpidetails = new HashSet<Fpidetail>(0);
	private Set<Piassignexternalaccessory> piassignexternalaccessories = new HashSet<Piassignexternalaccessory>(0);
	private Set<Rfpidetail> rfpidetails = new HashSet<Rfpidetail>(0);
	private Set<Fabricinformationdetail> fabricinformationdetails = new HashSet<Fabricinformationdetail>(0);
	private Set<Accessory> accessories = new HashSet<Accessory>(0);
	private Set<Pigriddetail> pigriddetails = new HashSet<Pigriddetail>(0);

	public Color() {
	}

	public Color(String colorcode) {
		this.colorcode = colorcode;
	}

	public Color(String colorcode, User user, String description, Date createdate,
			Set<Piassigninternalaccessoriesdetail> piassigninternalaccessoriesdetails,
			Set<Piassignfabricdetail> piassignfabricdetails, Set<Fpidetail> fpidetails,
			Set<Piassignexternalaccessory> piassignexternalaccessories, Set<Rfpidetail> rfpidetails,
			Set<Fabricinformationdetail> fabricinformationdetails, Set<Accessory> accessories,
			Set<Pigriddetail> pigriddetails) {
		this.colorcode = colorcode;
		this.user = user;
		this.description = description;
		this.createdate = createdate;
		this.piassigninternalaccessoriesdetails = piassigninternalaccessoriesdetails;
		this.piassignfabricdetails = piassignfabricdetails;
		this.fpidetails = fpidetails;
		this.piassignexternalaccessories = piassignexternalaccessories;
		this.rfpidetails = rfpidetails;
		this.fabricinformationdetails = fabricinformationdetails;
		this.accessories = accessories;
		this.pigriddetails = pigriddetails;
	}

	@Id

	@Column(name = "COLORCODE", unique = true, nullable = false, length = 20)
	public String getColorcode() {
		return this.colorcode;
	}

	public void setColorcode(String colorcode) {
		this.colorcode = colorcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Piassigninternalaccessoriesdetail> getPiassigninternalaccessoriesdetails() {
		return this.piassigninternalaccessoriesdetails;
	}

	public void setPiassigninternalaccessoriesdetails(
			Set<Piassigninternalaccessoriesdetail> piassigninternalaccessoriesdetails) {
		this.piassigninternalaccessoriesdetails = piassigninternalaccessoriesdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Piassignfabricdetail> getPiassignfabricdetails() {
		return this.piassignfabricdetails;
	}

	public void setPiassignfabricdetails(Set<Piassignfabricdetail> piassignfabricdetails) {
		this.piassignfabricdetails = piassignfabricdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Fpidetail> getFpidetails() {
		return this.fpidetails;
	}

	public void setFpidetails(Set<Fpidetail> fpidetails) {
		this.fpidetails = fpidetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Piassignexternalaccessory> getPiassignexternalaccessories() {
		return this.piassignexternalaccessories;
	}

	public void setPiassignexternalaccessories(Set<Piassignexternalaccessory> piassignexternalaccessories) {
		this.piassignexternalaccessories = piassignexternalaccessories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Rfpidetail> getRfpidetails() {
		return this.rfpidetails;
	}

	public void setRfpidetails(Set<Rfpidetail> rfpidetails) {
		this.rfpidetails = rfpidetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Fabricinformationdetail> getFabricinformationdetails() {
		return this.fabricinformationdetails;
	}

	public void setFabricinformationdetails(Set<Fabricinformationdetail> fabricinformationdetails) {
		this.fabricinformationdetails = fabricinformationdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Accessory> getAccessories() {
		return this.accessories;
	}

	public void setAccessories(Set<Accessory> accessories) {
		this.accessories = accessories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Pigriddetail> getPigriddetails() {
		return this.pigriddetails;
	}

	public void setPigriddetails(Set<Pigriddetail> pigriddetails) {
		this.pigriddetails = pigriddetails;
	}

}
