package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ctnrtype generated by hbm2java
 */
@Entity
@Table(name = "ctnrtype")
public class Ctnrtype implements java.io.Serializable {

	private String ctnrcode;
	private User user;
	private String description;
	private Date createdate;

	public Ctnrtype() {
	}

	public Ctnrtype(String ctnrcode) {
		this.ctnrcode = ctnrcode;
	}

	public Ctnrtype(String ctnrcode, User user, String description, Date createdate) {
		this.ctnrcode = ctnrcode;
		this.user = user;
		this.description = description;
		this.createdate = createdate;
	}

	@Id

	@Column(name = "CTNRCODE", unique = true, nullable = false, length = 20)
	public String getCtnrcode() {
		return this.ctnrcode;
	}

	public void setCtnrcode(String ctnrcode) {
		this.ctnrcode = ctnrcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
