package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estimatetime generated by hbm2java
 */
@Entity
@Table(name = "estimatetime")
public class Estimatetime implements java.io.Serializable {

	private Integer estimatetimecode;
	private User user;
	private Integer piconpletion;
	private Integer packingaccdelv;
	private Integer manuaccdelv;
	private Date createdate;

	public Estimatetime() {
	}

	public Estimatetime(User user, Integer piconpletion, Integer packingaccdelv, Integer manuaccdelv, Date createdate) {
		this.user = user;
		this.piconpletion = piconpletion;
		this.packingaccdelv = packingaccdelv;
		this.manuaccdelv = manuaccdelv;
		this.createdate = createdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ESTIMATETIMECODE", unique = true, nullable = false)
	public Integer getEstimatetimecode() {
		return this.estimatetimecode;
	}

	public void setEstimatetimecode(Integer estimatetimecode) {
		this.estimatetimecode = estimatetimecode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "PICONPLETION")
	public Integer getPiconpletion() {
		return this.piconpletion;
	}

	public void setPiconpletion(Integer piconpletion) {
		this.piconpletion = piconpletion;
	}

	@Column(name = "PACKINGACCDELV")
	public Integer getPackingaccdelv() {
		return this.packingaccdelv;
	}

	public void setPackingaccdelv(Integer packingaccdelv) {
		this.packingaccdelv = packingaccdelv;
	}

	@Column(name = "MANUACCDELV")
	public Integer getManuaccdelv() {
		return this.manuaccdelv;
	}

	public void setManuaccdelv(Integer manuaccdelv) {
		this.manuaccdelv = manuaccdelv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
