package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Externalaccessorystock generated by hbm2java
 */
@Entity
@Table(name = "externalaccessorystock")
public class Externalaccessorystock implements java.io.Serializable {

	private Integer externalaccessorystockcode;
	private Accessory accessory;
	private Factory factory;
	private Orderexternalaccessory orderexternalaccessory;
	private Float availableqty;
	private Set<Piassignexternalaccessory> piassignexternalaccessories = new HashSet<Piassignexternalaccessory>(0);

	public Externalaccessorystock() {
	}

	public Externalaccessorystock(Accessory accessory, Factory factory, Orderexternalaccessory orderexternalaccessory,
			Float availableqty, Set<Piassignexternalaccessory> piassignexternalaccessories) {
		this.accessory = accessory;
		this.factory = factory;
		this.orderexternalaccessory = orderexternalaccessory;
		this.availableqty = availableqty;
		this.piassignexternalaccessories = piassignexternalaccessories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EXTERNALACCESSORYSTOCKCODE", unique = true, nullable = false)
	public Integer getExternalaccessorystockcode() {
		return this.externalaccessorystockcode;
	}

	public void setExternalaccessorystockcode(Integer externalaccessorystockcode) {
		this.externalaccessorystockcode = externalaccessorystockcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCESSORYCODE")
	public Accessory getAccessory() {
		return this.accessory;
	}

	public void setAccessory(Accessory accessory) {
		this.accessory = accessory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FACTORYCODE")
	public Factory getFactory() {
		return this.factory;
	}

	public void setFactory(Factory factory) {
		this.factory = factory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDERSHEETNO")
	public Orderexternalaccessory getOrderexternalaccessory() {
		return this.orderexternalaccessory;
	}

	public void setOrderexternalaccessory(Orderexternalaccessory orderexternalaccessory) {
		this.orderexternalaccessory = orderexternalaccessory;
	}

	@Column(name = "AVAILABLEQTY", precision = 12, scale = 0)
	public Float getAvailableqty() {
		return this.availableqty;
	}

	public void setAvailableqty(Float availableqty) {
		this.availableqty = availableqty;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "externalaccessorystock")
	public Set<Piassignexternalaccessory> getPiassignexternalaccessories() {
		return this.piassignexternalaccessories;
	}

	public void setPiassignexternalaccessories(Set<Piassignexternalaccessory> piassignexternalaccessories) {
		this.piassignexternalaccessories = piassignexternalaccessories;
	}

}
