package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fabricinformation generated by hbm2java
 */
@Entity
@Table(name = "fabricinformation")
public class Fabricinformation implements java.io.Serializable {

	private String fabricno;
	private Agent agent;
	private Currency currency;
	private Customer customer;
	private Fabricsupplier fabricsupplier;
	private Factory factory;
	private User user;
	private Width width;
	private String fabricitem;
	private Boolean ischori;
	private String component;
	private Date estimatedelvdate;
	private Date actualdelvdate;
	private String fabricinvoiceno;
	private String fabricimgurl;
	private String remark;
	private Date createdate;
	private Date voucherreceiveddate;
	private Date vouchersentdate;
	private Set<Piassignfabric> piassignfabrics = new HashSet<Piassignfabric>(0);
	private Set<Fabricinformationdetail> fabricinformationdetails = new HashSet<Fabricinformationdetail>(0);

	public Fabricinformation() {
	}

	public Fabricinformation(String fabricno) {
		this.fabricno = fabricno;
	}

	public Fabricinformation(String fabricno, Agent agent, Currency currency, Customer customer,
			Fabricsupplier fabricsupplier, Factory factory, User user, Width width, String fabricitem, Boolean ischori,
			String component, Date estimatedelvdate, Date actualdelvdate, String fabricinvoiceno, String fabricimgurl,
			String remark, Date createdate, Date voucherreceiveddate, Date vouchersentdate,
			Set<Piassignfabric> piassignfabrics, Set<Fabricinformationdetail> fabricinformationdetails) {
		this.fabricno = fabricno;
		this.agent = agent;
		this.currency = currency;
		this.customer = customer;
		this.fabricsupplier = fabricsupplier;
		this.factory = factory;
		this.user = user;
		this.width = width;
		this.fabricitem = fabricitem;
		this.ischori = ischori;
		this.component = component;
		this.estimatedelvdate = estimatedelvdate;
		this.actualdelvdate = actualdelvdate;
		this.fabricinvoiceno = fabricinvoiceno;
		this.fabricimgurl = fabricimgurl;
		this.remark = remark;
		this.createdate = createdate;
		this.voucherreceiveddate = voucherreceiveddate;
		this.vouchersentdate = vouchersentdate;
		this.piassignfabrics = piassignfabrics;
		this.fabricinformationdetails = fabricinformationdetails;
	}

	@Id

	@Column(name = "FABRICNO", unique = true, nullable = false, length = 50)
	public String getFabricno() {
		return this.fabricno;
	}

	public void setFabricno(String fabricno) {
		this.fabricno = fabricno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AGENTCODE")
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCYCODE")
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMERCODE")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FABRICSUPCODE")
	public Fabricsupplier getFabricsupplier() {
		return this.fabricsupplier;
	}

	public void setFabricsupplier(Fabricsupplier fabricsupplier) {
		this.fabricsupplier = fabricsupplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FACTORYCODE")
	public Factory getFactory() {
		return this.factory;
	}

	public void setFactory(Factory factory) {
		this.factory = factory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WIDTHCODE")
	public Width getWidth() {
		return this.width;
	}

	public void setWidth(Width width) {
		this.width = width;
	}

	@Column(name = "FABRICITEM", length = 50)
	public String getFabricitem() {
		return this.fabricitem;
	}

	public void setFabricitem(String fabricitem) {
		this.fabricitem = fabricitem;
	}

	@Column(name = "ISCHORI")
	public Boolean getIschori() {
		return this.ischori;
	}

	public void setIschori(Boolean ischori) {
		this.ischori = ischori;
	}

	@Column(name = "COMPONENT", length = 500)
	public String getComponent() {
		return this.component;
	}

	public void setComponent(String component) {
		this.component = component;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ESTIMATEDELVDATE", length = 19)
	public Date getEstimatedelvdate() {
		return this.estimatedelvdate;
	}

	public void setEstimatedelvdate(Date estimatedelvdate) {
		this.estimatedelvdate = estimatedelvdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTUALDELVDATE", length = 19)
	public Date getActualdelvdate() {
		return this.actualdelvdate;
	}

	public void setActualdelvdate(Date actualdelvdate) {
		this.actualdelvdate = actualdelvdate;
	}

	@Column(name = "FABRICINVOICENO", length = 50)
	public String getFabricinvoiceno() {
		return this.fabricinvoiceno;
	}

	public void setFabricinvoiceno(String fabricinvoiceno) {
		this.fabricinvoiceno = fabricinvoiceno;
	}

	@Column(name = "FABRICIMGURL", length = 500)
	public String getFabricimgurl() {
		return this.fabricimgurl;
	}

	public void setFabricimgurl(String fabricimgurl) {
		this.fabricimgurl = fabricimgurl;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VOUCHERRECEIVEDDATE", length = 19)
	public Date getVoucherreceiveddate() {
		return this.voucherreceiveddate;
	}

	public void setVoucherreceiveddate(Date voucherreceiveddate) {
		this.voucherreceiveddate = voucherreceiveddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VOUCHERSENTDATE", length = 19)
	public Date getVouchersentdate() {
		return this.vouchersentdate;
	}

	public void setVouchersentdate(Date vouchersentdate) {
		this.vouchersentdate = vouchersentdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fabricinformation")
	public Set<Piassignfabric> getPiassignfabrics() {
		return this.piassignfabrics;
	}

	public void setPiassignfabrics(Set<Piassignfabric> piassignfabrics) {
		this.piassignfabrics = piassignfabrics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fabricinformation")
	public Set<Fabricinformationdetail> getFabricinformationdetails() {
		return this.fabricinformationdetails;
	}

	public void setFabricinformationdetails(Set<Fabricinformationdetail> fabricinformationdetails) {
		this.fabricinformationdetails = fabricinformationdetails;
	}

}
