package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fabricinformationdetail generated by hbm2java
 */
@Entity
@Table(name = "fabricinformationdetail")
public class Fabricinformationdetail implements java.io.Serializable {

	private FabricinformationdetailId id;
	private Color color;
	private Fabricinformation fabricinformation;
	private User user;
	private Float unitprice;
	private Double yardinbl;
	private String imgurl;
	private Date createdate;

	public Fabricinformationdetail() {
	}

	public Fabricinformationdetail(FabricinformationdetailId id, Color color, Fabricinformation fabricinformation) {
		this.id = id;
		this.color = color;
		this.fabricinformation = fabricinformation;
	}

	public Fabricinformationdetail(FabricinformationdetailId id, Color color, Fabricinformation fabricinformation,
			User user, Float unitprice, Double yardinbl, String imgurl, Date createdate) {
		this.id = id;
		this.color = color;
		this.fabricinformation = fabricinformation;
		this.user = user;
		this.unitprice = unitprice;
		this.yardinbl = yardinbl;
		this.imgurl = imgurl;
		this.createdate = createdate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fabricno", column = @Column(name = "FABRICNO", nullable = false, length = 50)),
			@AttributeOverride(name = "colorcode", column = @Column(name = "COLORCODE", nullable = false, length = 20)) })
	public FabricinformationdetailId getId() {
		return this.id;
	}

	public void setId(FabricinformationdetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COLORCODE", nullable = false, insertable = false, updatable = false)
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FABRICNO", nullable = false, insertable = false, updatable = false)
	public Fabricinformation getFabricinformation() {
		return this.fabricinformation;
	}

	public void setFabricinformation(Fabricinformation fabricinformation) {
		this.fabricinformation = fabricinformation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "UNITPRICE", precision = 20, scale = 4)
	public Float getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(Float unitprice) {
		this.unitprice = unitprice;
	}

	@Column(name = "YARDINBL", precision = 22, scale = 0)
	public Double getYardinbl() {
		return this.yardinbl;
	}

	public void setYardinbl(Double yardinbl) {
		this.yardinbl = yardinbl;
	}

	@Column(name = "IMGURL", length = 500)
	public String getImgurl() {
		return this.imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
