package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FabricinformationdetailId generated by hbm2java
 */
@Embeddable
public class FabricinformationdetailId implements java.io.Serializable {

	private String fabricno;
	private String colorcode;

	public FabricinformationdetailId() {
	}

	public FabricinformationdetailId(String fabricno, String colorcode) {
		this.fabricno = fabricno;
		this.colorcode = colorcode;
	}

	@Column(name = "FABRICNO", nullable = false, length = 50)
	public String getFabricno() {
		return this.fabricno;
	}

	public void setFabricno(String fabricno) {
		this.fabricno = fabricno;
	}

	@Column(name = "COLORCODE", nullable = false, length = 20)
	public String getColorcode() {
		return this.colorcode;
	}

	public void setColorcode(String colorcode) {
		this.colorcode = colorcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FabricinformationdetailId))
			return false;
		FabricinformationdetailId castOther = (FabricinformationdetailId) other;

		return ((this.getFabricno() == castOther.getFabricno()) || (this.getFabricno() != null
				&& castOther.getFabricno() != null && this.getFabricno().equals(castOther.getFabricno())))
				&& ((this.getColorcode() == castOther.getColorcode()) || (this.getColorcode() != null
						&& castOther.getColorcode() != null && this.getColorcode().equals(castOther.getColorcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFabricno() == null ? 0 : this.getFabricno().hashCode());
		result = 37 * result + (getColorcode() == null ? 0 : this.getColorcode().hashCode());
		return result;
	}

}
