package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factoryaccountinformation generated by hbm2java
 */
@Entity
@Table(name = "factoryaccountinformation")
public class Factoryaccountinformation implements java.io.Serializable {

	private Integer factoryaccountinfocode;
	private Factory factory;
	private User user;
	private String bankname;
	private String bankbranch;
	private String accountnumber;
	private String address;
	private String swiftcode;
	private Date createdate;

	public Factoryaccountinformation() {
	}

	public Factoryaccountinformation(Factory factory, User user, String bankname, String bankbranch,
			String accountnumber, String address, String swiftcode, Date createdate) {
		this.factory = factory;
		this.user = user;
		this.bankname = bankname;
		this.bankbranch = bankbranch;
		this.accountnumber = accountnumber;
		this.address = address;
		this.swiftcode = swiftcode;
		this.createdate = createdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FACTORYACCOUNTINFOCODE", unique = true, nullable = false)
	public Integer getFactoryaccountinfocode() {
		return this.factoryaccountinfocode;
	}

	public void setFactoryaccountinfocode(Integer factoryaccountinfocode) {
		this.factoryaccountinfocode = factoryaccountinfocode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FACTORYCODE")
	public Factory getFactory() {
		return this.factory;
	}

	public void setFactory(Factory factory) {
		this.factory = factory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "BANKNAME", length = 200)
	public String getBankname() {
		return this.bankname;
	}

	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	@Column(name = "BANKBRANCH", length = 200)
	public String getBankbranch() {
		return this.bankbranch;
	}

	public void setBankbranch(String bankbranch) {
		this.bankbranch = bankbranch;
	}

	@Column(name = "ACCOUNTNUMBER", length = 30)
	public String getAccountnumber() {
		return this.accountnumber;
	}

	public void setAccountnumber(String accountnumber) {
		this.accountnumber = accountnumber;
	}

	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "SWIFTCODE", length = 30)
	public String getSwiftcode() {
		return this.swiftcode;
	}

	public void setSwiftcode(String swiftcode) {
		this.swiftcode = swiftcode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
