package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Fpi generated by hbm2java
 */
@Entity
@Table(name = "fpi")
public class Fpi implements java.io.Serializable {

	private Integer fpicode;
	private Integer version;
	private Pi pi;
	private User user;
	private Date receiveddate;
	private String customerconfirmationstatus;
	private Date createdate;
	private Set<Fpidetail> fpidetails = new HashSet<Fpidetail>(0);

	public Fpi() {
	}

	public Fpi(Pi pi, User user, Date receiveddate, String customerconfirmationstatus, Date createdate,
			Set<Fpidetail> fpidetails) {
		this.pi = pi;
		this.user = user;
		this.receiveddate = receiveddate;
		this.customerconfirmationstatus = customerconfirmationstatus;
		this.createdate = createdate;
		this.fpidetails = fpidetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FPICODE", unique = true, nullable = false)
	public Integer getFpicode() {
		return this.fpicode;
	}

	public void setFpicode(Integer fpicode) {
		this.fpicode = fpicode;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOTNUMBER")
	public Pi getPi() {
		return this.pi;
	}

	public void setPi(Pi pi) {
		this.pi = pi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECEIVEDDATE", length = 19)
	public Date getReceiveddate() {
		return this.receiveddate;
	}

	public void setReceiveddate(Date receiveddate) {
		this.receiveddate = receiveddate;
	}

	@Column(name = "CUSTOMERCONFIRMATIONSTATUS", length = 20)
	public String getCustomerconfirmationstatus() {
		return this.customerconfirmationstatus;
	}

	public void setCustomerconfirmationstatus(String customerconfirmationstatus) {
		this.customerconfirmationstatus = customerconfirmationstatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpi")
	public Set<Fpidetail> getFpidetails() {
		return this.fpidetails;
	}

	public void setFpidetails(Set<Fpidetail> fpidetails) {
		this.fpidetails = fpidetails;
	}

}
