package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Function generated by hbm2java
 */
@Entity
@Table(name = "function")
public class Function implements java.io.Serializable {

	private String functionid;
	private String functionname;
	private String description;
	private Set<Role> roles = new HashSet<Role>(0);

	public Function() {
	}

	public Function(String functionid) {
		this.functionid = functionid;
	}

	public Function(String functionid, String functionname, String description, Set<Role> roles) {
		this.functionid = functionid;
		this.functionname = functionname;
		this.description = description;
		this.roles = roles;
	}

	@Id

	@Column(name = "FUNCTIONID", unique = true, nullable = false, length = 50)
	public String getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(String functionid) {
		this.functionid = functionid;
	}

	@Column(name = "FUNCTIONNAME", length = 100)
	public String getFunctionname() {
		return this.functionname;
	}

	public void setFunctionname(String functionname) {
		this.functionname = functionname;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "functions")
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
