package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GarmentstylereferpriceId generated by hbm2java
 */
@Embeddable
public class GarmentstylereferpriceId implements java.io.Serializable {

	private String garmentstylecode;
	private String typecode;

	public GarmentstylereferpriceId() {
	}

	public GarmentstylereferpriceId(String garmentstylecode, String typecode) {
		this.garmentstylecode = garmentstylecode;
		this.typecode = typecode;
	}

	@Column(name = "GARMENTSTYLECODE", nullable = false, length = 100)
	public String getGarmentstylecode() {
		return this.garmentstylecode;
	}

	public void setGarmentstylecode(String garmentstylecode) {
		this.garmentstylecode = garmentstylecode;
	}

	@Column(name = "TYPECODE", nullable = false, length = 20)
	public String getTypecode() {
		return this.typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GarmentstylereferpriceId))
			return false;
		GarmentstylereferpriceId castOther = (GarmentstylereferpriceId) other;

		return ((this.getGarmentstylecode() == castOther.getGarmentstylecode())
				|| (this.getGarmentstylecode() != null && castOther.getGarmentstylecode() != null
						&& this.getGarmentstylecode().equals(castOther.getGarmentstylecode())))
				&& ((this.getTypecode() == castOther.getTypecode()) || (this.getTypecode() != null
						&& castOther.getTypecode() != null && this.getTypecode().equals(castOther.getTypecode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGarmentstylecode() == null ? 0 : this.getGarmentstylecode().hashCode());
		result = 37 * result + (getTypecode() == null ? 0 : this.getTypecode().hashCode());
		return result;
	}

}
