package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logofchange generated by hbm2java
 */
@Entity
@Table(name = "logofchange")
public class Logofchange implements java.io.Serializable {

	private Integer logofchangecode;
	private Pi pi;
	private String subject;
	private String fromemail;
	private String toemail;
	private Date createdate;
	private String ccmailstring;
	private String attachedfileurl1;
	private String attachedfileurl2;
	private String attachedfileurl3;
	private String attachedfileurl4;
	private String attachedfileurl5;
	private String attachedfileurl6;
	private String attachedfileurl7;
	private String attachedfileurl8;
	private String attachedfileurl9;
	private String attachedfileurl10;

	public Logofchange() {
	}

	public Logofchange(Pi pi, String subject, String fromemail, String toemail, Date createdate, String ccmailstring,
			String attachedfileurl1, String attachedfileurl2, String attachedfileurl3, String attachedfileurl4,
			String attachedfileurl5, String attachedfileurl6, String attachedfileurl7, String attachedfileurl8,
			String attachedfileurl9, String attachedfileurl10) {
		this.pi = pi;
		this.subject = subject;
		this.fromemail = fromemail;
		this.toemail = toemail;
		this.createdate = createdate;
		this.ccmailstring = ccmailstring;
		this.attachedfileurl1 = attachedfileurl1;
		this.attachedfileurl2 = attachedfileurl2;
		this.attachedfileurl3 = attachedfileurl3;
		this.attachedfileurl4 = attachedfileurl4;
		this.attachedfileurl5 = attachedfileurl5;
		this.attachedfileurl6 = attachedfileurl6;
		this.attachedfileurl7 = attachedfileurl7;
		this.attachedfileurl8 = attachedfileurl8;
		this.attachedfileurl9 = attachedfileurl9;
		this.attachedfileurl10 = attachedfileurl10;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LOGOFCHANGECODE", unique = true, nullable = false)
	public Integer getLogofchangecode() {
		return this.logofchangecode;
	}

	public void setLogofchangecode(Integer logofchangecode) {
		this.logofchangecode = logofchangecode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOTNUMBER")
	public Pi getPi() {
		return this.pi;
	}

	public void setPi(Pi pi) {
		this.pi = pi;
	}

	@Column(name = "SUBJECT", length = 100)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "FROMEMAIL", length = 100)
	public String getFromemail() {
		return this.fromemail;
	}

	public void setFromemail(String fromemail) {
		this.fromemail = fromemail;
	}

	@Column(name = "TOEMAIL", length = 100)
	public String getToemail() {
		return this.toemail;
	}

	public void setToemail(String toemail) {
		this.toemail = toemail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "CCMAILSTRING", length = 500)
	public String getCcmailstring() {
		return this.ccmailstring;
	}

	public void setCcmailstring(String ccmailstring) {
		this.ccmailstring = ccmailstring;
	}

	@Column(name = "ATTACHEDFILEURL1", length = 65535)
	public String getAttachedfileurl1() {
		return this.attachedfileurl1;
	}

	public void setAttachedfileurl1(String attachedfileurl1) {
		this.attachedfileurl1 = attachedfileurl1;
	}

	@Column(name = "ATTACHEDFILEURL2", length = 65535)
	public String getAttachedfileurl2() {
		return this.attachedfileurl2;
	}

	public void setAttachedfileurl2(String attachedfileurl2) {
		this.attachedfileurl2 = attachedfileurl2;
	}

	@Column(name = "ATTACHEDFILEURL3", length = 65535)
	public String getAttachedfileurl3() {
		return this.attachedfileurl3;
	}

	public void setAttachedfileurl3(String attachedfileurl3) {
		this.attachedfileurl3 = attachedfileurl3;
	}

	@Column(name = "ATTACHEDFILEURL4", length = 65535)
	public String getAttachedfileurl4() {
		return this.attachedfileurl4;
	}

	public void setAttachedfileurl4(String attachedfileurl4) {
		this.attachedfileurl4 = attachedfileurl4;
	}

	@Column(name = "ATTACHEDFILEURL5", length = 65535)
	public String getAttachedfileurl5() {
		return this.attachedfileurl5;
	}

	public void setAttachedfileurl5(String attachedfileurl5) {
		this.attachedfileurl5 = attachedfileurl5;
	}

	@Column(name = "ATTACHEDFILEURL6", length = 65535)
	public String getAttachedfileurl6() {
		return this.attachedfileurl6;
	}

	public void setAttachedfileurl6(String attachedfileurl6) {
		this.attachedfileurl6 = attachedfileurl6;
	}

	@Column(name = "ATTACHEDFILEURL7", length = 65535)
	public String getAttachedfileurl7() {
		return this.attachedfileurl7;
	}

	public void setAttachedfileurl7(String attachedfileurl7) {
		this.attachedfileurl7 = attachedfileurl7;
	}

	@Column(name = "ATTACHEDFILEURL8", length = 65535)
	public String getAttachedfileurl8() {
		return this.attachedfileurl8;
	}

	public void setAttachedfileurl8(String attachedfileurl8) {
		this.attachedfileurl8 = attachedfileurl8;
	}

	@Column(name = "ATTACHEDFILEURL9", length = 65535)
	public String getAttachedfileurl9() {
		return this.attachedfileurl9;
	}

	public void setAttachedfileurl9(String attachedfileurl9) {
		this.attachedfileurl9 = attachedfileurl9;
	}

	@Column(name = "ATTACHEDFILEURL10", length = 65535)
	public String getAttachedfileurl10() {
		return this.attachedfileurl10;
	}

	public void setAttachedfileurl10(String attachedfileurl10) {
		this.attachedfileurl10 = attachedfileurl10;
	}

}
