package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orderexternalaccessory generated by hbm2java
 */
@Entity
@Table(name = "orderexternalaccessory")
public class Orderexternalaccessory implements java.io.Serializable {

	private String ordersheetno;
	private Accessory accessory;
	private Accessorysupplier accessorysupplier;
	private Factory factory;
	private User user;
	private Integer orderquantity;
	private Integer actualdelvquantity;
	private Date orderdate;
	private Date estimatedelvdate;
	private Date actualdelvdate;
	private String status;
	private String paymentstatus;
	private String remark;
	private Float price;
	private Date createdate;
	private Float unitprice;
	private Set<Piassignexternalaccessory> piassignexternalaccessories = new HashSet<Piassignexternalaccessory>(0);
	private Set<Externalaccessorystock> externalaccessorystocks = new HashSet<Externalaccessorystock>(0);

	public Orderexternalaccessory() {
	}

	public Orderexternalaccessory(String ordersheetno) {
		this.ordersheetno = ordersheetno;
	}

	public Orderexternalaccessory(String ordersheetno, Accessory accessory, Accessorysupplier accessorysupplier,
			Factory factory, User user, Integer orderquantity, Integer actualdelvquantity, Date orderdate,
			Date estimatedelvdate, Date actualdelvdate, String status, String paymentstatus, String remark, Float price,
			Date createdate, Float unitprice, Set<Piassignexternalaccessory> piassignexternalaccessories,
			Set<Externalaccessorystock> externalaccessorystocks) {
		this.ordersheetno = ordersheetno;
		this.accessory = accessory;
		this.accessorysupplier = accessorysupplier;
		this.factory = factory;
		this.user = user;
		this.orderquantity = orderquantity;
		this.actualdelvquantity = actualdelvquantity;
		this.orderdate = orderdate;
		this.estimatedelvdate = estimatedelvdate;
		this.actualdelvdate = actualdelvdate;
		this.status = status;
		this.paymentstatus = paymentstatus;
		this.remark = remark;
		this.price = price;
		this.createdate = createdate;
		this.unitprice = unitprice;
		this.piassignexternalaccessories = piassignexternalaccessories;
		this.externalaccessorystocks = externalaccessorystocks;
	}

	@Id

	@Column(name = "ORDERSHEETNO", unique = true, nullable = false, length = 50)
	public String getOrdersheetno() {
		return this.ordersheetno;
	}

	public void setOrdersheetno(String ordersheetno) {
		this.ordersheetno = ordersheetno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCESSORYCODE")
	public Accessory getAccessory() {
		return this.accessory;
	}

	public void setAccessory(Accessory accessory) {
		this.accessory = accessory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCSUPPLIERCODE")
	public Accessorysupplier getAccessorysupplier() {
		return this.accessorysupplier;
	}

	public void setAccessorysupplier(Accessorysupplier accessorysupplier) {
		this.accessorysupplier = accessorysupplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FACTORYCODE")
	public Factory getFactory() {
		return this.factory;
	}

	public void setFactory(Factory factory) {
		this.factory = factory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "ORDERQUANTITY")
	public Integer getOrderquantity() {
		return this.orderquantity;
	}

	public void setOrderquantity(Integer orderquantity) {
		this.orderquantity = orderquantity;
	}

	@Column(name = "ACTUALDELVQUANTITY")
	public Integer getActualdelvquantity() {
		return this.actualdelvquantity;
	}

	public void setActualdelvquantity(Integer actualdelvquantity) {
		this.actualdelvquantity = actualdelvquantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDERDATE", length = 19)
	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ESTIMATEDELVDATE", length = 19)
	public Date getEstimatedelvdate() {
		return this.estimatedelvdate;
	}

	public void setEstimatedelvdate(Date estimatedelvdate) {
		this.estimatedelvdate = estimatedelvdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTUALDELVDATE", length = 19)
	public Date getActualdelvdate() {
		return this.actualdelvdate;
	}

	public void setActualdelvdate(Date actualdelvdate) {
		this.actualdelvdate = actualdelvdate;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "PAYMENTSTATUS", length = 20)
	public String getPaymentstatus() {
		return this.paymentstatus;
	}

	public void setPaymentstatus(String paymentstatus) {
		this.paymentstatus = paymentstatus;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "PRICE", precision = 20, scale = 4)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "UNITPRICE", precision = 20, scale = 4)
	public Float getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(Float unitprice) {
		this.unitprice = unitprice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderexternalaccessory")
	public Set<Piassignexternalaccessory> getPiassignexternalaccessories() {
		return this.piassignexternalaccessories;
	}

	public void setPiassignexternalaccessories(Set<Piassignexternalaccessory> piassignexternalaccessories) {
		this.piassignexternalaccessories = piassignexternalaccessories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderexternalaccessory")
	public Set<Externalaccessorystock> getExternalaccessorystocks() {
		return this.externalaccessorystocks;
	}

	public void setExternalaccessorystocks(Set<Externalaccessorystock> externalaccessorystocks) {
		this.externalaccessorystocks = externalaccessorystocks;
	}

}
