package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orderinternalaccessory generated by hbm2java
 */
@Entity
@Table(name = "orderinternalaccessory")
public class Orderinternalaccessory implements java.io.Serializable {

	private String ordersheetno;
	private Accessorysupplier accessorysupplier;
	private Factory factory;
	private User user;
	private Date orderdate;
	private Date estimatedelvdate;
	private Date actualdelvdate;
	private String status;
	private String shippingstatus;
	private String remark;
	private Date createdate;
	private String invoicenumber;
	private Double unitprice;
	private Set<Piassigninternalaccessoriesoforders> piassigninternalaccessoriesoforderses = new HashSet<Piassigninternalaccessoriesoforders>(
			0);
	private Set<Orderinternalaccessorydetail> orderinternalaccessorydetails = new HashSet<Orderinternalaccessorydetail>(
			0);

	public Orderinternalaccessory() {
	}

	public Orderinternalaccessory(String ordersheetno) {
		this.ordersheetno = ordersheetno;
	}

	public Orderinternalaccessory(String ordersheetno, Accessorysupplier accessorysupplier, Factory factory, User user,
			Date orderdate, Date estimatedelvdate, Date actualdelvdate, String status, String shippingstatus, String remark, Date createdate,
			String invoicenumber, Double unitprice,
			Set<Piassigninternalaccessoriesoforders> piassigninternalaccessoriesoforderses,
			Set<Orderinternalaccessorydetail> orderinternalaccessorydetails) {
		this.ordersheetno = ordersheetno;
		this.accessorysupplier = accessorysupplier;
		this.factory = factory;
		this.user = user;
		this.orderdate = orderdate;
		this.estimatedelvdate = estimatedelvdate;
		this.actualdelvdate = actualdelvdate;
		this.status = status;
		this.remark = remark;
		this.createdate = createdate;
		this.invoicenumber = invoicenumber;
		this.shippingstatus = shippingstatus;
		this.unitprice = unitprice;
		this.piassigninternalaccessoriesoforderses = piassigninternalaccessoriesoforderses;
		this.orderinternalaccessorydetails = orderinternalaccessorydetails;
	}

	@Id

	@Column(name = "ORDERSHEETNO", unique = true, nullable = false, length = 50)
	public String getOrdersheetno() {
		return this.ordersheetno;
	}

	public void setOrdersheetno(String ordersheetno) {
		this.ordersheetno = ordersheetno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCSUPPLIERCODE")
	public Accessorysupplier getAccessorysupplier() {
		return this.accessorysupplier;
	}

	public void setAccessorysupplier(Accessorysupplier accessorysupplier) {
		this.accessorysupplier = accessorysupplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FACTORYCODE")
	public Factory getFactory() {
		return this.factory;
	}

	public void setFactory(Factory factory) {
		this.factory = factory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ORDERDATE", length = 19)
	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ESTIMATEDELVDATE", length = 19)
	public Date getEstimatedelvdate() {
		return this.estimatedelvdate;
	}

	public void setEstimatedelvdate(Date estimatedelvdate) {
		this.estimatedelvdate = estimatedelvdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ACTUALDELVDATE", length = 19)
	public Date getActualdelvdate() {
		return this.actualdelvdate;
	}

	public void setActualdelvdate(Date actualdelvdate) {
		this.actualdelvdate = actualdelvdate;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name = "SHIPPINGSTATUS", length = 20)
	public String getShippingstatus() {
		return this.shippingstatus;
	}

	public void setShippingstatus(String shippingstatus) {
		this.shippingstatus = shippingstatus;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "INVOICENUMBER", length = 50)
	public String getInvoicenumber() {
		return this.invoicenumber;
	}

	public void setInvoicenumber(String invoicenumber) {
		this.invoicenumber = invoicenumber;
	}

	@Column(name = "UNITPRICE", precision = 20, scale = 4)
	public Double getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(Double unitprice) {
		this.unitprice = unitprice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderinternalaccessory")
	public Set<Piassigninternalaccessoriesoforders> getPiassigninternalaccessoriesoforderses() {
		return this.piassigninternalaccessoriesoforderses;
	}

	public void setPiassigninternalaccessoriesoforderses(
			Set<Piassigninternalaccessoriesoforders> piassigninternalaccessoriesoforderses) {
		this.piassigninternalaccessoriesoforderses = piassigninternalaccessoriesoforderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderinternalaccessory")
	public Set<Orderinternalaccessorydetail> getOrderinternalaccessorydetails() {
		return this.orderinternalaccessorydetails;
	}

	public void setOrderinternalaccessorydetails(Set<Orderinternalaccessorydetail> orderinternalaccessorydetails) {
		this.orderinternalaccessorydetails = orderinternalaccessorydetails;
	}

}
