package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Piassigninternalaccessoriesoforders generated by hbm2java
 */
@Entity
@Table(name = "piassigninternalaccessoriesoforders")
public class Piassigninternalaccessoriesoforders implements java.io.Serializable {

	private Integer piassigninternalaccessoriesoforderscode;
	private Orderinternalaccessory orderinternalaccessory;
	private Piassigninternalaccessories piassigninternalaccessories;
	private Double orderassignquantity;

	public Piassigninternalaccessoriesoforders() {
	}

	public Piassigninternalaccessoriesoforders(Orderinternalaccessory orderinternalaccessory,
			Piassigninternalaccessories piassigninternalaccessories, Double orderassignquantity) {
		this.orderinternalaccessory = orderinternalaccessory;
		this.piassigninternalaccessories = piassigninternalaccessories;
		this.orderassignquantity = orderassignquantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PIASSIGNINTERNALACCESSORIESOFORDERSCODE", unique = true, nullable = false)
	public Integer getPiassigninternalaccessoriesoforderscode() {
		return this.piassigninternalaccessoriesoforderscode;
	}

	public void setPiassigninternalaccessoriesoforderscode(Integer piassigninternalaccessoriesoforderscode) {
		this.piassigninternalaccessoriesoforderscode = piassigninternalaccessoriesoforderscode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDERSHEETNO")
	public Orderinternalaccessory getOrderinternalaccessory() {
		return this.orderinternalaccessory;
	}

	public void setOrderinternalaccessory(Orderinternalaccessory orderinternalaccessory) {
		this.orderinternalaccessory = orderinternalaccessory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PIINTERNALACCESSORIES")
	public Piassigninternalaccessories getPiassigninternalaccessories() {
		return this.piassigninternalaccessories;
	}

	public void setPiassigninternalaccessories(Piassigninternalaccessories piassigninternalaccessories) {
		this.piassigninternalaccessories = piassigninternalaccessories;
	}

	@Column(name = "ORDERASSIGNQUANTITY")
	public Double getOrderassignquantity() {
		return this.orderassignquantity;
	}

	public void setOrderassignquantity(Double orderassignquantity) {
		this.orderassignquantity = orderassignquantity;
	}

}
