package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Piassignfabricdetail generated by hbm2java
 */
@Entity
@Table(name = "piassignfabricdetail")
public class Piassignfabricdetail implements java.io.Serializable {

	private Integer piassignfabricdetailcode;
	private Color color;
	private Garmentstyle garmentstyle;
	private Piassignfabric piassignfabric;
	private Integer assignquantity;
	private Float assignqtypercent;
	private Date createdate;

	public Piassignfabricdetail() {
	}

	public Piassignfabricdetail(Color color, Garmentstyle garmentstyle, Piassignfabric piassignfabric,
			Integer assignquantity, Float assignqtypercent, Date createdate) {
		this.color = color;
		this.garmentstyle = garmentstyle;
		this.piassignfabric = piassignfabric;
		this.assignquantity = assignquantity;
		this.assignqtypercent = assignqtypercent;
		this.createdate = createdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PIASSIGNFABRICDETAILCODE", unique = true, nullable = false)
	public Integer getPiassignfabricdetailcode() {
		return this.piassignfabricdetailcode;
	}

	public void setPiassignfabricdetailcode(Integer piassignfabricdetailcode) {
		this.piassignfabricdetailcode = piassignfabricdetailcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COLORCODE")
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GARMENTSTYLECODE")
	public Garmentstyle getGarmentstyle() {
		return this.garmentstyle;
	}

	public void setGarmentstyle(Garmentstyle garmentstyle) {
		this.garmentstyle = garmentstyle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "LOTNUMBER", referencedColumnName = "LOTNUMBER"),
			@JoinColumn(name = "FABRICNO", referencedColumnName = "FABRICNO") })
	public Piassignfabric getPiassignfabric() {
		return this.piassignfabric;
	}

	public void setPiassignfabric(Piassignfabric piassignfabric) {
		this.piassignfabric = piassignfabric;
	}

	@Column(name = "ASSIGNQUANTITY")
	public Integer getAssignquantity() {
		return this.assignquantity;
	}

	public void setAssignquantity(Integer assignquantity) {
		this.assignquantity = assignquantity;
	}

	@Column(name = "ASSIGNQTYPERCENT", precision = 20, scale = 4)
	public Float getAssignqtypercent() {
		return this.assignqtypercent;
	}

	public void setAssignqtypercent(Float assignqtypercent) {
		this.assignqtypercent = assignqtypercent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
