package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PiassignfabricId generated by hbm2java
 */
@Embeddable
public class PiassignfabricId implements java.io.Serializable {

	private String lotnumber;
	private String fabricno;

	public PiassignfabricId() {
	}

	public PiassignfabricId(String lotnumber, String fabricno) {
		this.lotnumber = lotnumber;
		this.fabricno = fabricno;
	}

	@Column(name = "LOTNUMBER", nullable = false, length = 50)
	public String getLotnumber() {
		return this.lotnumber;
	}

	public void setLotnumber(String lotnumber) {
		this.lotnumber = lotnumber;
	}

	@Column(name = "FABRICNO", nullable = false, length = 50)
	public String getFabricno() {
		return this.fabricno;
	}

	public void setFabricno(String fabricno) {
		this.fabricno = fabricno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PiassignfabricId))
			return false;
		PiassignfabricId castOther = (PiassignfabricId) other;

		return ((this.getLotnumber() == castOther.getLotnumber()) || (this.getLotnumber() != null
				&& castOther.getLotnumber() != null && this.getLotnumber().equals(castOther.getLotnumber())))
				&& ((this.getFabricno() == castOther.getFabricno()) || (this.getFabricno() != null
						&& castOther.getFabricno() != null && this.getFabricno().equals(castOther.getFabricno())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLotnumber() == null ? 0 : this.getLotnumber().hashCode());
		result = 37 * result + (getFabricno() == null ? 0 : this.getFabricno().hashCode());
		return result;
	}

}
