package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Piassignfabric generated by hbm2java
 */
@Entity
@Table(name = "piassignfabric")
public class Piassignfabric implements java.io.Serializable {

	private PiassignfabricId id;
	private Fabricinformation fabricinformation;
	private Pi pi;
	private User user;
	private Date createdate;
	private Set<Piassignfabricdetail> piassignfabricdetails = new HashSet<Piassignfabricdetail>(0);

	public Piassignfabric() {
	}

	public Piassignfabric(PiassignfabricId id, Fabricinformation fabricinformation, Pi pi) {
		this.id = id;
		this.fabricinformation = fabricinformation;
		this.pi = pi;
	}

	public Piassignfabric(PiassignfabricId id, Fabricinformation fabricinformation, Pi pi, User user, Date createdate,
			Set<Piassignfabricdetail> piassignfabricdetails) {
		this.id = id;
		this.fabricinformation = fabricinformation;
		this.pi = pi;
		this.user = user;
		this.createdate = createdate;
		this.piassignfabricdetails = piassignfabricdetails;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "lotnumber", column = @Column(name = "LOTNUMBER", nullable = false, length = 50)),
			@AttributeOverride(name = "fabricno", column = @Column(name = "FABRICNO", nullable = false, length = 50)) })
	public PiassignfabricId getId() {
		return this.id;
	}

	public void setId(PiassignfabricId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FABRICNO", nullable = false, insertable = false, updatable = false)
	public Fabricinformation getFabricinformation() {
		return this.fabricinformation;
	}

	public void setFabricinformation(Fabricinformation fabricinformation) {
		this.fabricinformation = fabricinformation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOTNUMBER", nullable = false, insertable = false, updatable = false)
	public Pi getPi() {
		return this.pi;
	}

	public void setPi(Pi pi) {
		this.pi = pi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "piassignfabric")
	public Set<Piassignfabricdetail> getPiassignfabricdetails() {
		return this.piassignfabricdetails;
	}

	public void setPiassignfabricdetails(Set<Piassignfabricdetail> piassignfabricdetails) {
		this.piassignfabricdetails = piassignfabricdetails;
	}

}
