package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pigrid generated by hbm2java
 */
@Entity
@Table(name = "pigrid")
public class Pigrid implements java.io.Serializable {

	private Integer pigridcode;
	private User user;
	private Date createdate;
	private Set<Pigriddetail> pigriddetails = new HashSet<Pigriddetail>(0);
	private Set<Pi> pis = new HashSet<Pi>(0);

	public Pigrid() {
	}

	public Pigrid(User user, Date createdate, Set<Pigriddetail> pigriddetails, Set<Pi> pis) {
		this.user = user;
		this.createdate = createdate;
		this.pigriddetails = pigriddetails;
		this.pis = pis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PIGRIDCODE", unique = true, nullable = false)
	public Integer getPigridcode() {
		return this.pigridcode;
	}

	public void setPigridcode(Integer pigridcode) {
		this.pigridcode = pigridcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pigrid")
	public Set<Pigriddetail> getPigriddetails() {
		return this.pigriddetails;
	}

	public void setPigriddetails(Set<Pigriddetail> pigriddetails) {
		this.pigriddetails = pigriddetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pigrid")
	public Set<Pi> getPis() {
		return this.pis;
	}

	public void setPis(Set<Pi> pis) {
		this.pis = pis;
	}

}
