package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pigriddetail generated by hbm2java
 */
@Entity
@Table(name = "pigriddetail")
public class Pigriddetail implements java.io.Serializable {

	private Integer pigriddetail;
	private Color color;
	private Garmentstyle garmentstyle;
	private Pigrid pigrid;
	private Size size;
	private String barcode;
	private Integer pcs;
	private Integer favalue;
	private Set<Piassignexternalaccessory> piassignexternalaccessories = new HashSet<Piassignexternalaccessory>(0);

	public Pigriddetail() {
	}

	public Pigriddetail(Color color, Garmentstyle garmentstyle, Pigrid pigrid, Size size, String barcode, Integer pcs,
			Integer favalue, Set<Piassignexternalaccessory> piassignexternalaccessories) {
		this.color = color;
		this.garmentstyle = garmentstyle;
		this.pigrid = pigrid;
		this.size = size;
		this.barcode = barcode;
		this.pcs = pcs;
		this.favalue = favalue;
		this.piassignexternalaccessories = piassignexternalaccessories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PIGRIDDETAIL", unique = true, nullable = false)
	public Integer getPigriddetail() {
		return this.pigriddetail;
	}

	public void setPigriddetail(Integer pigriddetail) {
		this.pigriddetail = pigriddetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COLORCODE")
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GARMENTSTYLECODE")
	public Garmentstyle getGarmentstyle() {
		return this.garmentstyle;
	}

	public void setGarmentstyle(Garmentstyle garmentstyle) {
		this.garmentstyle = garmentstyle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PIGRIDCODE")
	public Pigrid getPigrid() {
		return this.pigrid;
	}

	public void setPigrid(Pigrid pigrid) {
		this.pigrid = pigrid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SIZECODE")
	public Size getSize() {
		return this.size;
	}

	public void setSize(Size size) {
		this.size = size;
	}

	@Column(name = "BARCODE", length = 50)
	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	@Column(name = "PCS")
	public Integer getPcs() {
		return this.pcs;
	}

	public void setPcs(Integer pcs) {
		this.pcs = pcs;
	}

	@Column(name = "FAVALUE")
	public Integer getFavalue() {
		return this.favalue;
	}

	public void setFavalue(Integer favalue) {
		this.favalue = favalue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pigriddetail")
	public Set<Piassignexternalaccessory> getPiassignexternalaccessories() {
		return this.piassignexternalaccessories;
	}

	public void setPiassignexternalaccessories(Set<Piassignexternalaccessory> piassignexternalaccessories) {
		this.piassignexternalaccessories = piassignexternalaccessories;
	}

}
