package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rfpidetail generated by hbm2java
 */
@Entity
@Table(name = "rfpidetail")
public class Rfpidetail implements java.io.Serializable {

	private Integer rfpidetail;
	private Color color;
	private Garmentstyle garmentstyle;
	private Rfpi rfpi;
	private Size size;
	private Integer rfpivalue;

	public Rfpidetail() {
	}

	public Rfpidetail(Color color, Garmentstyle garmentstyle, Rfpi rfpi, Size size, Integer rfpivalue) {
		this.color = color;
		this.garmentstyle = garmentstyle;
		this.rfpi = rfpi;
		this.size = size;
		this.rfpivalue = rfpivalue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RFPIDETAIL", unique = true, nullable = false)
	public Integer getRfpidetail() {
		return this.rfpidetail;
	}

	public void setRfpidetail(Integer rfpidetail) {
		this.rfpidetail = rfpidetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COLORCODE")
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GARMENTSTYLECODE")
	public Garmentstyle getGarmentstyle() {
		return this.garmentstyle;
	}

	public void setGarmentstyle(Garmentstyle garmentstyle) {
		this.garmentstyle = garmentstyle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RFPIGRID")
	public Rfpi getRfpi() {
		return this.rfpi;
	}

	public void setRfpi(Rfpi rfpi) {
		this.rfpi = rfpi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SIZECODE")
	public Size getSize() {
		return this.size;
	}

	public void setSize(Size size) {
		this.size = size;
	}

	@Column(name = "RFPIVALUE")
	public Integer getRfpivalue() {
		return this.rfpivalue;
	}

	public void setRfpivalue(Integer rfpivalue) {
		this.rfpivalue = rfpivalue;
	}

}
