package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shippinglinecontact generated by hbm2java
 */
@Entity
@Table(name = "shippinglinecontact")
public class Shippinglinecontact implements java.io.Serializable {

	private Integer shippinglinecontactcode;
	private Shippingline shippingline;
	private User user;
	private String name;
	private String email;
	private Date createdate;
	private String tel;

	public Shippinglinecontact() {
	}

	public Shippinglinecontact(Shippingline shippingline, User user, String name, String email, Date createdate,
			String tel) {
		this.shippingline = shippingline;
		this.user = user;
		this.name = name;
		this.email = email;
		this.createdate = createdate;
		this.tel = tel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SHIPPINGLINECONTACTCODE", unique = true, nullable = false)
	public Integer getShippinglinecontactcode() {
		return this.shippinglinecontactcode;
	}

	public void setShippinglinecontactcode(Integer shippinglinecontactcode) {
		this.shippinglinecontactcode = shippinglinecontactcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SHIPPINGLINECODE")
	public Shippingline getShippingline() {
		return this.shippingline;
	}

	public void setShippingline(Shippingline shippingline) {
		this.shippingline = shippingline;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "TEL", length = 50)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

}
