package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shippingline generated by hbm2java
 */
@Entity
@Table(name = "shippingline")
public class Shippingline implements java.io.Serializable {

	private String shippinglinecode;
	private User user;
	private String shortname;
	private String longname;
	private String address;
	private String tel;
	private String fax;
	private String taxno;
	private String status;
	private Date createdate;
	private String remark;
	private Set<Shippinglinecontact> shippinglinecontacts = new HashSet<Shippinglinecontact>(0);

	public Shippingline() {
	}

	public Shippingline(String shippinglinecode, String shortname) {
		this.shippinglinecode = shippinglinecode;
		this.shortname = shortname;
	}

	public Shippingline(String shippinglinecode, User user, String shortname, String longname, String address,
			String tel, String fax, String taxno, String status, Date createdate, String remark,
			Set<Shippinglinecontact> shippinglinecontacts) {
		this.shippinglinecode = shippinglinecode;
		this.user = user;
		this.shortname = shortname;
		this.longname = longname;
		this.address = address;
		this.tel = tel;
		this.fax = fax;
		this.taxno = taxno;
		this.status = status;
		this.createdate = createdate;
		this.remark = remark;
		this.shippinglinecontacts = shippinglinecontacts;
	}

	@Id

	@Column(name = "SHIPPINGLINECODE", unique = true, nullable = false, length = 50)
	public String getShippinglinecode() {
		return this.shippinglinecode;
	}

	public void setShippinglinecode(String shippinglinecode) {
		this.shippinglinecode = shippinglinecode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "SHORTNAME", nullable = false, length = 50)
	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	@Column(name = "LONGNAME", length = 100)
	public String getLongname() {
		return this.longname;
	}

	public void setLongname(String longname) {
		this.longname = longname;
	}

	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "TEL", length = 50)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "FAX", length = 50)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "TAXNO", length = 50)
	public String getTaxno() {
		return this.taxno;
	}

	public void setTaxno(String taxno) {
		this.taxno = taxno;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shippingline")
	public Set<Shippinglinecontact> getShippinglinecontacts() {
		return this.shippinglinecontacts;
	}

	public void setShippinglinecontacts(Set<Shippinglinecontact> shippinglinecontacts) {
		this.shippinglinecontacts = shippinglinecontacts;
	}

}
