package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type")
public class Type implements java.io.Serializable {

	private String typecode;
	private User user;
	private String description;
	private Date createdate;
	private Set<Size> sizes = new HashSet<Size>(0);
	private Set<Garmentstylereferprice> garmentstylereferprices = new HashSet<Garmentstylereferprice>(0);

	public Type() {
	}

	public Type(String typecode) {
		this.typecode = typecode;
	}

	public Type(String typecode, User user, String description, Date createdate, Set<Size> sizes,
			Set<Garmentstylereferprice> garmentstylereferprices) {
		this.typecode = typecode;
		this.user = user;
		this.description = description;
		this.createdate = createdate;
		this.sizes = sizes;
		this.garmentstylereferprices = garmentstylereferprices;
	}

	@Id

	@Column(name = "TYPECODE", unique = true, nullable = false, length = 20)
	public String getTypecode() {
		return this.typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Size> getSizes() {
		return this.sizes;
	}

	public void setSizes(Set<Size> sizes) {
		this.sizes = sizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Garmentstylereferprice> getGarmentstylereferprices() {
		return this.garmentstylereferprices;
	}

	public void setGarmentstylereferprices(Set<Garmentstylereferprice> garmentstylereferprices) {
		this.garmentstylereferprices = garmentstylereferprices;
	}

}
