package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name = "unit")
public class Unit implements java.io.Serializable {

	private String unitcode;
	private String name;
	private Date createdate;
	private Set<Accessory> accessoriesForUnitcode = new HashSet<Accessory>(0);
	private Set<Width> widths = new HashSet<Width>(0);
	private Set<Accessory> accessoriesForContainerunitcode = new HashSet<Accessory>(0);
	private Set<Garmentstylereferprice> garmentstylereferprices = new HashSet<Garmentstylereferprice>(0);

	public Unit() {
	}

	public Unit(String unitcode) {
		this.unitcode = unitcode;
	}

	public Unit(String unitcode, String name, Date createdate, Set<Accessory> accessoriesForUnitcode, Set<Width> widths,
			Set<Accessory> accessoriesForContainerunitcode, Set<Garmentstylereferprice> garmentstylereferprices) {
		this.unitcode = unitcode;
		this.name = name;
		this.createdate = createdate;
		this.accessoriesForUnitcode = accessoriesForUnitcode;
		this.widths = widths;
		this.accessoriesForContainerunitcode = accessoriesForContainerunitcode;
		this.garmentstylereferprices = garmentstylereferprices;
	}

	@Id

	@Column(name = "UNITCODE", unique = true, nullable = false, length = 20)
	public String getUnitcode() {
		return this.unitcode;
	}

	public void setUnitcode(String unitcode) {
		this.unitcode = unitcode;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitByUnitcode")
	public Set<Accessory> getAccessoriesForUnitcode() {
		return this.accessoriesForUnitcode;
	}

	public void setAccessoriesForUnitcode(Set<Accessory> accessoriesForUnitcode) {
		this.accessoriesForUnitcode = accessoriesForUnitcode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unit")
	public Set<Width> getWidths() {
		return this.widths;
	}

	public void setWidths(Set<Width> widths) {
		this.widths = widths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitByContainerunitcode")
	public Set<Accessory> getAccessoriesForContainerunitcode() {
		return this.accessoriesForContainerunitcode;
	}

	public void setAccessoriesForContainerunitcode(Set<Accessory> accessoriesForContainerunitcode) {
		this.accessoriesForContainerunitcode = accessoriesForContainerunitcode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unit")
	public Set<Garmentstylereferprice> getGarmentstylereferprices() {
		return this.garmentstylereferprices;
	}

	public void setGarmentstylereferprices(Set<Garmentstylereferprice> garmentstylereferprices) {
		this.garmentstylereferprices = garmentstylereferprices;
	}

}
