package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	private String username;
	private Agent agent;
	private Role role;
	private User user;
	private String password;
	private String firstname;
	private String lastname;
	private String email;
	private String emailpassword;
	private String phone;
	private String status;
	private Boolean ccmailstring;
	private Set<Ctnrtype> ctnrtypes = new HashSet<Ctnrtype>(0);
	private Set<Garmentconsumptiondetail> garmentconsumptiondetails = new HashSet<Garmentconsumptiondetail>(0);
	private Set<Destination> destinations = new HashSet<Destination>(0);
	private Set<Accessoryformdetail> accessoryformdetails = new HashSet<Accessoryformdetail>(0);
	private Set<Agent> agents = new HashSet<Agent>(0);
	private Set<Garmentstyle> garmentstyles = new HashSet<Garmentstyle>(0);
	private Set<Currency> currencies = new HashSet<Currency>(0);
	private Set<Accessorysupplier> accessorysuppliers = new HashSet<Accessorysupplier>(0);
	private Set<Garmentkind> garmentkinds = new HashSet<Garmentkind>(0);
	private Set<Accessoryprice> accessoryprices = new HashSet<Accessoryprice>(0);
	private Set<Factoryaccountinformation> factoryaccountinformations = new HashSet<Factoryaccountinformation>(0);
	private Set<Pi> pis = new HashSet<Pi>(0);
	private Set<Fabricinformation> fabricinformations = new HashSet<Fabricinformation>(0);
	private Set<Shippingline> shippinglines = new HashSet<Shippingline>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Garmentconsumption> garmentconsumptions = new HashSet<Garmentconsumption>(0);
	private Set<Accessorygroup> accessorygroups = new HashSet<Accessorygroup>(0);
	private Set<Packingguide> packingguides = new HashSet<Packingguide>(0);
	private Set<Factorycontact> factorycontacts = new HashSet<Factorycontact>(0);
	private Set<Agentcontact> agentcontacts = new HashSet<Agentcontact>(0);
	private Set<Size> sizes = new HashSet<Size>(0);
	private Set<Garmentstyleaccessorydetail> garmentstyleaccessorydetails = new HashSet<Garmentstyleaccessorydetail>(0);
	private Set<Piassigninternalaccessories> piassigninternalaccessorieses = new HashSet<Piassigninternalaccessories>(
			0);
	private Set<Accessory> accessories = new HashSet<Accessory>(0);
	private Set<Customercontact> customercontacts = new HashSet<Customercontact>(0);
	private Set<Piassignfabric> piassignfabrics = new HashSet<Piassignfabric>(0);
	private Set<Estimatetime> estimatetimes = new HashSet<Estimatetime>(0);
	private Set<Accessoryordersignature> accessoryordersignatures = new HashSet<Accessoryordersignature>(0);
	private Set<Brand> brands = new HashSet<Brand>(0);
	private Set<Rfpi> rfpis = new HashSet<Rfpi>(0);
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<Shippinglinecontact> shippinglinecontacts = new HashSet<Shippinglinecontact>(0);
	private Set<Accessoryform> accessoryforms = new HashSet<Accessoryform>(0);
	private Set<Color> colors = new HashSet<Color>(0);
	private Set<Pigrid> pigrids = new HashSet<Pigrid>(0);
	private Set<Fabricinformationdetail> fabricinformationdetails = new HashSet<Fabricinformationdetail>(0);
	private Set<Orderinternalaccessorydetail> orderinternalaccessorydetails = new HashSet<Orderinternalaccessorydetail>(
			0);
	private Set<Accessorysuppliercontact> accessorysuppliercontacts = new HashSet<Accessorysuppliercontact>(0);
	private Set<Factory> factories = new HashSet<Factory>(0);
	private Set<Width> widths = new HashSet<Width>(0);
	private Set<Piassignexternalaccessory> piassignexternalaccessories = new HashSet<Piassignexternalaccessory>(0);
	private Set<Type> types = new HashSet<Type>(0);
	private Set<Fabricsuppliercontact> fabricsuppliercontacts = new HashSet<Fabricsuppliercontact>(0);
	private Set<Orderinternalaccessory> orderinternalaccessories = new HashSet<Orderinternalaccessory>(0);
	private Set<Fabricsupplier> fabricsuppliers = new HashSet<Fabricsupplier>(0);
	private Set<Fpi> fpis = new HashSet<Fpi>(0);
	private Set<Customeraccountinformation> customeraccountinformations = new HashSet<Customeraccountinformation>(0);
	private Set<Accessoryconsumption> accessoryconsumptions = new HashSet<Accessoryconsumption>(0);
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<Orderexternalaccessory> orderexternalaccessories = new HashSet<Orderexternalaccessory>(0);

	public User() {
	}

	public User(String username) {
		this.username = username;
	}

	public User(String username, Agent agent, Role role, User user, String password, String firstname, String lastname,
			String email, String emailpassword, String phone, String status, Boolean ccmailstring,
			Set<Ctnrtype> ctnrtypes, Set<Garmentconsumptiondetail> garmentconsumptiondetails,
			Set<Destination> destinations, Set<Accessoryformdetail> accessoryformdetails, Set<Agent> agents,
			Set<Garmentstyle> garmentstyles, Set<Currency> currencies, Set<Accessorysupplier> accessorysuppliers,
			Set<Garmentkind> garmentkinds, Set<Accessoryprice> accessoryprices,
			Set<Factoryaccountinformation> factoryaccountinformations, Set<Pi> pis,
			Set<Fabricinformation> fabricinformations, Set<Shippingline> shippinglines, Set<User> users,
			Set<Garmentconsumption> garmentconsumptions, Set<Accessorygroup> accessorygroups,
			Set<Packingguide> packingguides, Set<Factorycontact> factorycontacts, Set<Agentcontact> agentcontacts,
			Set<Size> sizes, Set<Garmentstyleaccessorydetail> garmentstyleaccessorydetails,
			Set<Piassigninternalaccessories> piassigninternalaccessorieses, Set<Accessory> accessories,
			Set<Customercontact> customercontacts, Set<Piassignfabric> piassignfabrics, Set<Estimatetime> estimatetimes,
			Set<Accessoryordersignature> accessoryordersignatures, Set<Brand> brands, Set<Rfpi> rfpis,
			Set<Customer> customers, Set<Shippinglinecontact> shippinglinecontacts, Set<Accessoryform> accessoryforms,
			Set<Color> colors, Set<Pigrid> pigrids, Set<Fabricinformationdetail> fabricinformationdetails,
			Set<Orderinternalaccessorydetail> orderinternalaccessorydetails,
			Set<Accessorysuppliercontact> accessorysuppliercontacts, Set<Factory> factories, Set<Width> widths,
			Set<Piassignexternalaccessory> piassignexternalaccessories, Set<Type> types,
			Set<Fabricsuppliercontact> fabricsuppliercontacts, Set<Orderinternalaccessory> orderinternalaccessories,
			Set<Fabricsupplier> fabricsuppliers, Set<Fpi> fpis,
			Set<Customeraccountinformation> customeraccountinformations,
			Set<Accessoryconsumption> accessoryconsumptions, Set<Role> roles,
			Set<Orderexternalaccessory> orderexternalaccessories) {
		this.username = username;
		this.agent = agent;
		this.role = role;
		this.user = user;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.emailpassword = emailpassword;
		this.phone = phone;
		this.status = status;
		this.ccmailstring = ccmailstring;
		this.ctnrtypes = ctnrtypes;
		this.garmentconsumptiondetails = garmentconsumptiondetails;
		this.destinations = destinations;
		this.accessoryformdetails = accessoryformdetails;
		this.agents = agents;
		this.garmentstyles = garmentstyles;
		this.currencies = currencies;
		this.accessorysuppliers = accessorysuppliers;
		this.garmentkinds = garmentkinds;
		this.accessoryprices = accessoryprices;
		this.factoryaccountinformations = factoryaccountinformations;
		this.pis = pis;
		this.fabricinformations = fabricinformations;
		this.shippinglines = shippinglines;
		this.users = users;
		this.garmentconsumptions = garmentconsumptions;
		this.accessorygroups = accessorygroups;
		this.packingguides = packingguides;
		this.factorycontacts = factorycontacts;
		this.agentcontacts = agentcontacts;
		this.sizes = sizes;
		this.garmentstyleaccessorydetails = garmentstyleaccessorydetails;
		this.piassigninternalaccessorieses = piassigninternalaccessorieses;
		this.accessories = accessories;
		this.customercontacts = customercontacts;
		this.piassignfabrics = piassignfabrics;
		this.estimatetimes = estimatetimes;
		this.accessoryordersignatures = accessoryordersignatures;
		this.brands = brands;
		this.rfpis = rfpis;
		this.customers = customers;
		this.shippinglinecontacts = shippinglinecontacts;
		this.accessoryforms = accessoryforms;
		this.colors = colors;
		this.pigrids = pigrids;
		this.fabricinformationdetails = fabricinformationdetails;
		this.orderinternalaccessorydetails = orderinternalaccessorydetails;
		this.accessorysuppliercontacts = accessorysuppliercontacts;
		this.factories = factories;
		this.widths = widths;
		this.piassignexternalaccessories = piassignexternalaccessories;
		this.types = types;
		this.fabricsuppliercontacts = fabricsuppliercontacts;
		this.orderinternalaccessories = orderinternalaccessories;
		this.fabricsuppliers = fabricsuppliers;
		this.fpis = fpis;
		this.customeraccountinformations = customeraccountinformations;
		this.accessoryconsumptions = accessoryconsumptions;
		this.roles = roles;
		this.orderexternalaccessories = orderexternalaccessories;
	}

	@Id

	@Column(name = "USERNAME", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AGENTCODE")
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLEID")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "PASSWORD", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "FIRSTNAME", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "EMAILPASSWORD", length = 100)
	public String getEmailpassword() {
		return this.emailpassword;
	}

	public void setEmailpassword(String emailpassword) {
		this.emailpassword = emailpassword;
	}

	@Column(name = "PHONE", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CCMAILSTRING")
	public Boolean getCcmailstring() {
		return this.ccmailstring;
	}

	public void setCcmailstring(Boolean ccmailstring) {
		this.ccmailstring = ccmailstring;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Ctnrtype> getCtnrtypes() {
		return this.ctnrtypes;
	}

	public void setCtnrtypes(Set<Ctnrtype> ctnrtypes) {
		this.ctnrtypes = ctnrtypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Garmentconsumptiondetail> getGarmentconsumptiondetails() {
		return this.garmentconsumptiondetails;
	}

	public void setGarmentconsumptiondetails(Set<Garmentconsumptiondetail> garmentconsumptiondetails) {
		this.garmentconsumptiondetails = garmentconsumptiondetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Destination> getDestinations() {
		return this.destinations;
	}

	public void setDestinations(Set<Destination> destinations) {
		this.destinations = destinations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessoryformdetail> getAccessoryformdetails() {
		return this.accessoryformdetails;
	}

	public void setAccessoryformdetails(Set<Accessoryformdetail> accessoryformdetails) {
		this.accessoryformdetails = accessoryformdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Agent> getAgents() {
		return this.agents;
	}

	public void setAgents(Set<Agent> agents) {
		this.agents = agents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Garmentstyle> getGarmentstyles() {
		return this.garmentstyles;
	}

	public void setGarmentstyles(Set<Garmentstyle> garmentstyles) {
		this.garmentstyles = garmentstyles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Currency> getCurrencies() {
		return this.currencies;
	}

	public void setCurrencies(Set<Currency> currencies) {
		this.currencies = currencies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessorysupplier> getAccessorysuppliers() {
		return this.accessorysuppliers;
	}

	public void setAccessorysuppliers(Set<Accessorysupplier> accessorysuppliers) {
		this.accessorysuppliers = accessorysuppliers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Garmentkind> getGarmentkinds() {
		return this.garmentkinds;
	}

	public void setGarmentkinds(Set<Garmentkind> garmentkinds) {
		this.garmentkinds = garmentkinds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessoryprice> getAccessoryprices() {
		return this.accessoryprices;
	}

	public void setAccessoryprices(Set<Accessoryprice> accessoryprices) {
		this.accessoryprices = accessoryprices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Factoryaccountinformation> getFactoryaccountinformations() {
		return this.factoryaccountinformations;
	}

	public void setFactoryaccountinformations(Set<Factoryaccountinformation> factoryaccountinformations) {
		this.factoryaccountinformations = factoryaccountinformations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Pi> getPis() {
		return this.pis;
	}

	public void setPis(Set<Pi> pis) {
		this.pis = pis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Fabricinformation> getFabricinformations() {
		return this.fabricinformations;
	}

	public void setFabricinformations(Set<Fabricinformation> fabricinformations) {
		this.fabricinformations = fabricinformations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Shippingline> getShippinglines() {
		return this.shippinglines;
	}

	public void setShippinglines(Set<Shippingline> shippinglines) {
		this.shippinglines = shippinglines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Garmentconsumption> getGarmentconsumptions() {
		return this.garmentconsumptions;
	}

	public void setGarmentconsumptions(Set<Garmentconsumption> garmentconsumptions) {
		this.garmentconsumptions = garmentconsumptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessorygroup> getAccessorygroups() {
		return this.accessorygroups;
	}

	public void setAccessorygroups(Set<Accessorygroup> accessorygroups) {
		this.accessorygroups = accessorygroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Packingguide> getPackingguides() {
		return this.packingguides;
	}

	public void setPackingguides(Set<Packingguide> packingguides) {
		this.packingguides = packingguides;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Factorycontact> getFactorycontacts() {
		return this.factorycontacts;
	}

	public void setFactorycontacts(Set<Factorycontact> factorycontacts) {
		this.factorycontacts = factorycontacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Agentcontact> getAgentcontacts() {
		return this.agentcontacts;
	}

	public void setAgentcontacts(Set<Agentcontact> agentcontacts) {
		this.agentcontacts = agentcontacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Size> getSizes() {
		return this.sizes;
	}

	public void setSizes(Set<Size> sizes) {
		this.sizes = sizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Garmentstyleaccessorydetail> getGarmentstyleaccessorydetails() {
		return this.garmentstyleaccessorydetails;
	}

	public void setGarmentstyleaccessorydetails(Set<Garmentstyleaccessorydetail> garmentstyleaccessorydetails) {
		this.garmentstyleaccessorydetails = garmentstyleaccessorydetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Piassigninternalaccessories> getPiassigninternalaccessorieses() {
		return this.piassigninternalaccessorieses;
	}

	public void setPiassigninternalaccessorieses(Set<Piassigninternalaccessories> piassigninternalaccessorieses) {
		this.piassigninternalaccessorieses = piassigninternalaccessorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessory> getAccessories() {
		return this.accessories;
	}

	public void setAccessories(Set<Accessory> accessories) {
		this.accessories = accessories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Customercontact> getCustomercontacts() {
		return this.customercontacts;
	}

	public void setCustomercontacts(Set<Customercontact> customercontacts) {
		this.customercontacts = customercontacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Piassignfabric> getPiassignfabrics() {
		return this.piassignfabrics;
	}

	public void setPiassignfabrics(Set<Piassignfabric> piassignfabrics) {
		this.piassignfabrics = piassignfabrics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Estimatetime> getEstimatetimes() {
		return this.estimatetimes;
	}

	public void setEstimatetimes(Set<Estimatetime> estimatetimes) {
		this.estimatetimes = estimatetimes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessoryordersignature> getAccessoryordersignatures() {
		return this.accessoryordersignatures;
	}

	public void setAccessoryordersignatures(Set<Accessoryordersignature> accessoryordersignatures) {
		this.accessoryordersignatures = accessoryordersignatures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Brand> getBrands() {
		return this.brands;
	}

	public void setBrands(Set<Brand> brands) {
		this.brands = brands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Rfpi> getRfpis() {
		return this.rfpis;
	}

	public void setRfpis(Set<Rfpi> rfpis) {
		this.rfpis = rfpis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Shippinglinecontact> getShippinglinecontacts() {
		return this.shippinglinecontacts;
	}

	public void setShippinglinecontacts(Set<Shippinglinecontact> shippinglinecontacts) {
		this.shippinglinecontacts = shippinglinecontacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessoryform> getAccessoryforms() {
		return this.accessoryforms;
	}

	public void setAccessoryforms(Set<Accessoryform> accessoryforms) {
		this.accessoryforms = accessoryforms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Color> getColors() {
		return this.colors;
	}

	public void setColors(Set<Color> colors) {
		this.colors = colors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Pigrid> getPigrids() {
		return this.pigrids;
	}

	public void setPigrids(Set<Pigrid> pigrids) {
		this.pigrids = pigrids;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Fabricinformationdetail> getFabricinformationdetails() {
		return this.fabricinformationdetails;
	}

	public void setFabricinformationdetails(Set<Fabricinformationdetail> fabricinformationdetails) {
		this.fabricinformationdetails = fabricinformationdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Orderinternalaccessorydetail> getOrderinternalaccessorydetails() {
		return this.orderinternalaccessorydetails;
	}

	public void setOrderinternalaccessorydetails(Set<Orderinternalaccessorydetail> orderinternalaccessorydetails) {
		this.orderinternalaccessorydetails = orderinternalaccessorydetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessorysuppliercontact> getAccessorysuppliercontacts() {
		return this.accessorysuppliercontacts;
	}

	public void setAccessorysuppliercontacts(Set<Accessorysuppliercontact> accessorysuppliercontacts) {
		this.accessorysuppliercontacts = accessorysuppliercontacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Factory> getFactories() {
		return this.factories;
	}

	public void setFactories(Set<Factory> factories) {
		this.factories = factories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Width> getWidths() {
		return this.widths;
	}

	public void setWidths(Set<Width> widths) {
		this.widths = widths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Piassignexternalaccessory> getPiassignexternalaccessories() {
		return this.piassignexternalaccessories;
	}

	public void setPiassignexternalaccessories(Set<Piassignexternalaccessory> piassignexternalaccessories) {
		this.piassignexternalaccessories = piassignexternalaccessories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Type> getTypes() {
		return this.types;
	}

	public void setTypes(Set<Type> types) {
		this.types = types;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Fabricsuppliercontact> getFabricsuppliercontacts() {
		return this.fabricsuppliercontacts;
	}

	public void setFabricsuppliercontacts(Set<Fabricsuppliercontact> fabricsuppliercontacts) {
		this.fabricsuppliercontacts = fabricsuppliercontacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Orderinternalaccessory> getOrderinternalaccessories() {
		return this.orderinternalaccessories;
	}

	public void setOrderinternalaccessories(Set<Orderinternalaccessory> orderinternalaccessories) {
		this.orderinternalaccessories = orderinternalaccessories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Fabricsupplier> getFabricsuppliers() {
		return this.fabricsuppliers;
	}

	public void setFabricsuppliers(Set<Fabricsupplier> fabricsuppliers) {
		this.fabricsuppliers = fabricsuppliers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Fpi> getFpis() {
		return this.fpis;
	}

	public void setFpis(Set<Fpi> fpis) {
		this.fpis = fpis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Customeraccountinformation> getCustomeraccountinformations() {
		return this.customeraccountinformations;
	}

	public void setCustomeraccountinformations(Set<Customeraccountinformation> customeraccountinformations) {
		this.customeraccountinformations = customeraccountinformations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Accessoryconsumption> getAccessoryconsumptions() {
		return this.accessoryconsumptions;
	}

	public void setAccessoryconsumptions(Set<Accessoryconsumption> accessoryconsumptions) {
		this.accessoryconsumptions = accessoryconsumptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Orderexternalaccessory> getOrderexternalaccessories() {
		return this.orderexternalaccessories;
	}

	public void setOrderexternalaccessories(Set<Orderexternalaccessory> orderexternalaccessories) {
		this.orderexternalaccessories = orderexternalaccessories;
	}

}
