package com.chori.entity;
// Generated Dec 8, 2016 6:21:17 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Width generated by hbm2java
 */
@Entity
@Table(name = "width")
public class Width implements java.io.Serializable {

	private String widthcode;
	private Unit unit;
	private User user;
	private String widthvalues;
	private Date createdate;
	private Set<Fabricinformation> fabricinformations = new HashSet<Fabricinformation>(0);
	private Set<Garmentconsumptiondetail> garmentconsumptiondetails = new HashSet<Garmentconsumptiondetail>(0);

	public Width() {
	}

	public Width(String widthcode) {
		this.widthcode = widthcode;
	}

	public Width(String widthcode, Unit unit, User user, String widthvalues, Date createdate,
			Set<Fabricinformation> fabricinformations, Set<Garmentconsumptiondetail> garmentconsumptiondetails) {
		this.widthcode = widthcode;
		this.unit = unit;
		this.user = user;
		this.widthvalues = widthvalues;
		this.createdate = createdate;
		this.fabricinformations = fabricinformations;
		this.garmentconsumptiondetails = garmentconsumptiondetails;
	}

	@Id

	@Column(name = "WIDTHCODE", unique = true, nullable = false, length = 20)
	public String getWidthcode() {
		return this.widthcode;
	}

	public void setWidthcode(String widthcode) {
		this.widthcode = widthcode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNITCODE")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "WIDTHVALUES", length = 20)
	public String getWidthvalues() {
		return this.widthvalues;
	}

	public void setWidthvalues(String widthvalues) {
		this.widthvalues = widthvalues;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "width")
	public Set<Fabricinformation> getFabricinformations() {
		return this.fabricinformations;
	}

	public void setFabricinformations(Set<Fabricinformation> fabricinformations) {
		this.fabricinformations = fabricinformations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "width")
	public Set<Garmentconsumptiondetail> getGarmentconsumptiondetails() {
		return this.garmentconsumptiondetails;
	}

	public void setGarmentconsumptiondetails(Set<Garmentconsumptiondetail> garmentconsumptiondetails) {
		this.garmentconsumptiondetails = garmentconsumptiondetails;
	}

}
